local_epochs: 10 # DEFINE NUMBER OF LOCAL EPOCHS HERE

batch_size: 0.5 # DEFINE BATCH SIZE HERE, int for regular batch size, float for specified utilization fraction (batch=0.70, 70% GPU memory utilization).